task:
  name: Test (x86)
  container:
    dockerfile: .ci/Dockerfile.x86
    cpu: 4
    memory: 10G
    kvm: true
  pub_cache:
    folder: ~/.pub-cache
  start_emulator_background_script:
    - sudo chown cirrus:cirrus /dev/kvm
    - $ANDROID_HOME/emulator/emulator-headless -version
    - $ANDROID_HOME/emulator/emulator-headless -avd test -no-audio -no-window
  wait_for_emulator_script:
    - ./script/android-wait-for-emulator.sh
    - adb shell input keyevent 82
  doctor_script: flutter doctor -v
  test_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter drive test_driver/main.dart
